import { useMemo, useState } from 'react';
import { getTripDestinations, getTripEndDate, getTripStartDate } from '../../core/travelSegment';
import { AnnualReflection, LedgerEntry, Trip, TripInsights } from '../../types/logbook';
import CrossTripIntelligence from '../CrossTripIntelligence';
import { useTripCover } from '../../hooks/useTripCover';
import LogbookAnalytics from './LogbookAnalytics';
interface Props { annualReflection: AnnualReflection; activeTrip: Trip|null; plannedTrips: Trip[]; tripInsights: TripInsights[]; reflectionTrips: Trip[]; }
const num=(v:number)=>new Intl.NumberFormat(undefined,{maximumFractionDigits:0}).format(v);
const date=(v:number)=>new Date(v).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});
const entryDate=(e:LedgerEntry)=>e.entryType==='flight'?e.outboundDate:e.paymentDate;
const signed=(e:LedgerEntry)=>e.isRefund?-e.cnyEquivalent:e.cnyEquivalent;
const days=(t:Trip)=>Math.max(1,Math.floor((getTripEndDate(t)-getTripStartDate(t))/86400000)+1);
export const LogbookView=({annualReflection,activeTrip,plannedTrips,tripInsights,reflectionTrips}:Props)=>{
 const defaultTripId=activeTrip?.id??reflectionTrips.find(t=>t.status==='achieve')?.id??reflectionTrips.find(t=>t.status==='planning')?.id??reflectionTrips[0]?.id??null;
 const [selectedTripId,setSelectedTripId]=useState<string|null>(defaultTripId);
 const [selectedEntryId,setSelectedEntryId]=useState<string|null>(null);
 const selectedTrip=useMemo(()=>reflectionTrips.find(t=>t.id===selectedTripId)??null,[reflectionTrips,selectedTripId]);
 const coverSrc=useTripCover(selectedTrip?.coverImage);
 const insight=selectedTrip?tripInsights.find(i=>i.tripId===selectedTrip.id)??null:null;
 const total=selectedTrip?selectedTrip.ledger.filter(e=>!e.isPending).reduce((s,e)=>s+signed(e),0):0;
 const people=selectedTrip?.members.filter(m=>m.archived!==true).length??0;
 const segmentCount=selectedTrip?.segments.length??0;
 const topExpense=selectedTrip?[...selectedTrip.ledger].filter(e=>!e.isPending).sort((a,b)=>Math.abs(b.cnyEquivalent)-Math.abs(a.cnyEquivalent))[0]:null;
 const topCategory=useMemo(()=>{if(!selectedTrip)return null;const m=new Map<string,number>();selectedTrip.ledger.filter(e=>!e.isPending).forEach(e=>{const n=selectedTrip.categories.find(c=>c.id===e.categoryId)?.name??'Uncategorized';m.set(n,(m.get(n)??0)+signed(e));});return [...m].filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1])[0]??null;},[selectedTrip]);
 const selectedEntry=selectedTrip?.ledger.find(e=>e.id===selectedEntryId)??null;
 const openTrip=(t:Trip)=>{setSelectedTripId(t.id);setSelectedEntryId(null)};
 return <main className="logbook-page">
  <header className="logbook-header"><div><p className="logbook-kicker">LOGBOOK / {annualReflection.year}</p><h1>Logbook</h1><p className="logbook-subtitle">A financial record of where the journey took you.</p></div></header>
  <section className="logbook-journey-card"><div className="logbook-journey-cover">{coverSrc?<img src={coverSrc} alt="" />:<span>✦</span>}</div><div><span className="logbook-overline">THIS JOURNEY</span><h2>{selectedTrip?.title||'Choose a journey'}</h2><p>{selectedTrip?getTripDestinations(selectedTrip).join(' · ')||'Destination not set':'No journey selected'}</p>{selectedTrip&&<small>{date(getTripStartDate(selectedTrip))} — {date(getTripEndDate(selectedTrip))} · {days(selectedTrip)} days · {people} travelers</small>}</div><select aria-label="Select journey" value={selectedTrip?.id??''} onChange={e=>setSelectedTripId(e.target.value)}>{reflectionTrips.map(t=><option key={t.id} value={t.id}>{t.title||getTripDestinations(t).join(' · ')||'Untitled journey'}</option>)}</select></section>
  {selectedTrip&&<section className="logbook-section logbook-glance"><div className="logbook-section-heading"><div><span className="logbook-overline">THE JOURNEY AT A GLANCE</span><h2>One trip, clearly seen.</h2></div></div><div className="logbook-glance-grid"><article><span>TOTAL EXPENSE</span><strong>¥{num(total)}</strong></article><article><span>DAILY AVG</span><strong>¥{num(total/days(selectedTrip))}</strong></article><article><span>PER PERSON</span><strong>¥{num(total/Math.max(1,people))}</strong></article><article><span>ENTRIES</span><strong>{selectedTrip.ledger.filter(e=>!e.isPending).length}</strong></article></div><div className="logbook-facts">{days(selectedTrip)} DAYS · {segmentCount} SEGMENTS · {people} PEOPLE</div></section>}
  <LogbookAnalytics trip={selectedTrip}/>
  {selectedTrip&&<section className="logbook-section"><div className="logbook-section-heading"><div><span className="logbook-overline">LARGEST EXPENSES</span><h2>The big ones.</h2></div></div><div className="logbook-expenses">{selectedTrip.ledger.filter(e=>!e.isPending).sort((a,b)=>Math.abs(b.cnyEquivalent)-Math.abs(a.cnyEquivalent)).slice(0,5).map((e,i)=><div key={e.id}><b>{String(i+1).padStart(2,'0')}</b><span>{selectedTrip.categories.find(c=>c.id===e.categoryId)?.name??'Uncategorized'}</span><strong>{e.isRefund?'−':''}¥{num(e.cnyEquivalent)}</strong></div>)}</div></section>}
  {selectedTrip&&<section className="logbook-section"><div className="logbook-section-heading"><div><span className="logbook-overline">SETTLEMENT</span><h2>Who owes whom.</h2></div></div><button type="button" className="logbook-settlement-link" onClick={()=>window.location.hash='Settlement'}>Open Settlement →</button></section>}
  {selectedTrip&&<section className="logbook-section"><div className="logbook-section-heading"><div><span className="logbook-overline">JOURNEY IN NUMBERS</span><h2>What this journey leaves behind.</h2></div></div><div className="logbook-number-grid"><article><strong>{days(selectedTrip)}</strong><span>DAYS</span></article><article><strong>{segmentCount}</strong><span>SEGMENTS</span></article><article><strong>{people}</strong><span>PEOPLE</span></article><article><strong>{selectedTrip.categories.length}</strong><span>CATEGORIES</span></article></div><div className="logbook-reflection-facts">{topExpense&&<span>Largest expense · {selectedTrip.categories.find(c=>c.id===topExpense.categoryId)?.name??'Expense'} · ¥{num(Math.abs(topExpense.cnyEquivalent))}</span>}{topCategory&&<span>Top category · {topCategory[0]} · {total?Math.round(topCategory[1]/Math.max(1,total)*100):0}%</span>}{insight?.expenseStructure?.[0]&&<span>Leading category · {insight.expenseStructure[0].category}</span>}</div></section>}
  {tripInsights.length>0&&<section className="logbook-section"><div className="logbook-section-heading"><div><span className="logbook-overline">JOURNEY HISTORY</span><h2>Journeys worth revisiting.</h2></div><span className="logbook-count">{tripInsights.length}</span></div><div className="logbook-trip-list">{tripInsights.map(i=>{const t=reflectionTrips.find(x=>x.id===i.tripId);if(!t)return null;return <button key={t.id} className="logbook-trip-card logbook-trip-button" type="button" onClick={()=>openTrip(t)}><div className="logbook-trip-top"><span>{t.title||getTripDestinations(t).join(' · ')||'Untitled journey'}</span><strong>{i.totalDays} DAYS</strong></div><div className="logbook-trip-body"><div><small>SPEND</small>{Object.entries(i.totalExpenditure).map(([c,a])=><strong key={c}>{num(a)} <em>{c}</em></strong>)}</div><div><small>PER DAY</small>{Object.entries(i.averageCostPerDay).map(([c,a])=><strong key={c}>{num(a)} <em>{c}</em></strong>)}</div></div><span className="logbook-drill-hint">View journey →</span></button>})}</div></section>}
  {reflectionTrips.filter(t=>t.status==='achieve').length>1&&<CrossTripIntelligence trips={reflectionTrips.filter(t=>t.status==='achieve')}/>} 
  <section className="logbook-note"><div className="logbook-note-kicker">A note from this journey</div><div className="logbook-note-copy">{selectedTrip?days(selectedTrip)+' days across '+segmentCount+' segments, with '+selectedTrip.ledger.filter(e=>!e.isPending).length+' recorded expenses.':'Complete a journey to begin your reflection.'}</div></section>
  {plannedTrips.length>0&&<section className="logbook-section logbook-planning"><div className="logbook-section-heading"><div><span className="logbook-overline">ON THE HORIZON</span><h2>Planning next</h2></div></div><div className="logbook-planned-list">{plannedTrips.map(t=><div className="logbook-planned-card" key={t.id}><strong>{t.title||'Untitled journey'}</strong><span>{getTripDestinations(t).join(' · ')||'Destination not set'}</span><small>{date(getTripStartDate(t))} — {date(getTripEndDate(t))}</small></div>)}</div></section>}
  {selectedEntry&&selectedTrip&&<div className="logbook-entry-detail"><div className="logbook-entry-detail-header"><div><span className="logbook-overline">LEDGER DETAIL</span><h3>{selectedTrip.categories.find(c=>c.id===selectedEntry.categoryId)?.name||'Uncategorized'}</h3></div><button className="logbook-close-button" type="button" onClick={()=>setSelectedEntryId(null)}>×</button></div><div className="logbook-entry-amount">{selectedEntry.isRefund?'−':''}¥{num(selectedEntry.cnyEquivalent)}</div><dl><div><dt>Date</dt><dd>{date(entryDate(selectedEntry))}</dd></div><div><dt>Payer</dt><dd>{selectedTrip.members.find(m=>m.id===selectedEntry.payerId)?.name||'Unknown'}</dd></div><div><dt>Account</dt><dd>{selectedTrip.accounts.find(a=>a.id===selectedEntry.accountId)?.name||'Unknown'}</dd></div></dl></div>}
 </main>;
};
export default LogbookView;