import { Trip } from '../core/domain';

const clean = (value: string) => value.trim();
const unique = (values: string[]) => [...new Set(values.map(clean).filter(Boolean))];
const datePrefix = (trip: Trip) => {
  const starts = trip.segments.map((segment) => segment.startDate).filter(Number.isFinite);
  if (!starts.length) return '';
  const date = new Date(Math.min(...starts));
  return date.getFullYear() + '.' + String(date.getMonth() + 1).padStart(2, '0');
};

const destinationData = (trip: Trip) => {
  const destinations = trip.segments.flatMap((segment) => segment.destinations);
  const countries = unique(destinations.map((destination) => destination.country));
  const isChina = countries.some((country) => /^(china|中国)$/i.test(country));
  const regions = unique(destinations.map((destination) => destination.region ?? ''));
  const base = isChina && regions.length ? regions[0] : (countries[0] ?? '');
  const cities = unique(destinations.map((destination) => destination.city));
  return { countries, base, cities };
};

const groupKey = (trip: Trip) => {
  const { countries, base } = destinationData(trip);
  if (!base) return '';
  const isChina = countries.some((country) => /^(china|中国)$/i.test(country));
  return isChina && base.toLowerCase() !== 'china' && base !== '中国' ? 'cn:' + base.toLocaleLowerCase() : 'country:' + base.toLocaleLowerCase();
};

const legacyAutoTitle = (trip: Trip) => {
  const prefix = datePrefix(trip);
  const cities = unique(trip.segments.flatMap((segment) => segment.destinations.map((destination) => destination.city)));
  return prefix && cities.length ? prefix + ' · ' + cities.join(' · ') : '';
};

export const isLikelyAutoGeneratedTitle = (trip: Trip) => {
  if (typeof trip.titleEdited === 'boolean') return !trip.titleEdited;
  return clean(trip.title) === legacyAutoTitle(trip);
};

export const buildAutoTripTitle = (trip: Trip, allTrips: Trip[]) => {
  const prefix = datePrefix(trip);
  if (!prefix) return '';
  const { base, cities } = destinationData(trip);
  if (!base) return '';
  const key = groupKey(trip);
  const sameGroupCount = key ? allTrips.filter((item) => item.id !== trip.id && groupKey(item) === key).length + 1 : 1;
  const suffix = sameGroupCount > 1 && cities.length ? ' · ' + cities.join(' · ') : '';
  return prefix + ' · ' + base + suffix;
};

export const refreshAutoTripTitles = (trips: Trip[]) => trips.map((trip) =>
  isLikelyAutoGeneratedTitle(trip) ? { ...trip, title: buildAutoTripTitle(trip, trips) } : trip,
);