import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Check, ChevronRight, Copy, Pencil, Plus, Trash2, X } from 'lucide-react';
import { listStats, TRAVEL_LIST_TEMPLATES } from '../../utils/travelLists';
import { useVelaStore } from '../../store/useVelaStore';
import './travelLists.css';

type Props = { tripId: string; listId?: string | null; onClose: () => void };
const pct=(n:number,d:number)=>d?Math.round(n/d*100):0;

export default function TravelLists({tripId,listId,onClose}:Props){
 const trips=useVelaStore(s=>s.trips);
 const addList=useVelaStore(s=>s.addList), addListTemplate=useVelaStore(s=>s.addListTemplate), addListFromTrip=useVelaStore(s=>s.addListFromTrip), addListItem=useVelaStore(s=>s.addListItem), updateList=useVelaStore(s=>s.updateList), updateListItem=useVelaStore(s=>s.updateListItem), deleteList=useVelaStore(s=>s.deleteList), deleteListItem=useVelaStore(s=>s.deleteListItem), ensureTripListsForTrip=useVelaStore(s=>s.ensureTripListsForTrip);
 const trip=trips.find(t=>t.id===tripId); const [selected,setSelected]=useState<string|null>(listId??null);
 useEffect(()=>{ensureTripListsForTrip(tripId)},[tripId,ensureTripListsForTrip]); const [showTemplates,setShowTemplates]=useState(false); const [showSources,setShowSources]=useState(false); const [sourceTripId,setSourceTripId]=useState(''); const [checked,setChecked]=useState<string[]>([]); const [itemDraft,setItemDraft]=useState('');
 const lists=trip?.lists??[]; const active=lists.find(l=>l.id===selected)??null;
 const all=useMemo(()=>lists.reduce((s,l)=>s+listStats(l).completed,0),[lists]); const total=useMemo(()=>lists.reduce((s,l)=>s+l.items.length,0),[lists]);
 if(!trip)return <main className="travel-lists"><button className="tl-back" onClick={onClose}><ArrowLeft size={15}/> Home</button><p>Trip not found.</p></main>;
 const addNew=()=>{const name=window.prompt('List name');if(name)try{addList(trip.id,name)}catch(e){window.alert(e instanceof Error?e.message:'Unable to add list.')}};
 const addTemplate=(template:typeof TRAVEL_LIST_TEMPLATES[number])=>{try{addListTemplate(trip.id,template);setShowTemplates(false)}catch(e){window.alert(e instanceof Error?e.message:'Unable to add template.')}};
 const renameList=()=>{if(!active)return;const name=window.prompt('List name',active.name);if(name&&name.trim()!==active.name.trim())try{updateList(trip.id,{...active,name:name.trim()})}catch(e){window.alert(e instanceof Error?e.message:'Unable to rename list.')}};
 const renameItem=(itemId:string,current:string)=>{const title=window.prompt('Item',current);if(title&&title.trim()!==current.trim())try{updateListItem(trip.id,active!.id,itemId,{title:title.trim()})}catch(e){window.alert(e instanceof Error?e.message:'Unable to edit item.')}};
 const addItems=()=>{const title=itemDraft.trim();if(!title||!active)return;try{addListItem(trip.id,active.id,title);setItemDraft('')}catch(e){window.alert(e instanceof Error?e.message:'Unable to add item.')}};
 const copySelected=()=>{if(!sourceTripId||!checked.length)return;try{addListFromTrip(trip.id,sourceTripId,checked);setShowSources(false);setChecked([])}catch(e){window.alert(e instanceof Error?e.message:'Unable to copy lists.')}};
 if(active)return <main className="travel-lists"><button className="tl-back" onClick={()=>setSelected(null)}><ArrowLeft size={15}/> {trip.title}</button><header className="tl-header"><div><span>LIST</span><h1>{active.name}</h1><p>{listStats(active).completed} / {active.items.length}</p></div><div className="tl-header-actions"><button className="tl-icon" onClick={renameList}><Pencil size={15}/></button><button className="tl-icon" onClick={()=>{if(window.confirm('Delete this list?')){deleteList(trip.id,active.id);setSelected(null)}}}><Trash2 size={16}/></button></div></header><div className="tl-progress"><i style={{width:pct(listStats(active).completed,active.items.length)+'%'}}/></div><section className="tl-items">{active.items.length?active.items.slice().sort((a,b)=>a.sortOrder-b.sortOrder).map(item=><div className={item.completed?'tl-item done':'tl-item'} key={item.id}><button className="tl-check" onClick={()=>updateListItem(trip.id,active.id,item.id,{completed:!item.completed})}>{item.completed&&<Check size={13}/>}</button><button className="tl-item-title" onClick={()=>renameItem(item.id,item.title)}>{item.title}</button><button className="tl-delete" onClick={()=>deleteListItem(trip.id,active.id,item.id)}><X size={13}/></button></div>):<div className="tl-empty">NO ITEMS YET.</div>}</section><form className="tl-add-item" onSubmit={e=>{e.preventDefault();addItems()}}><input value={itemDraft} onChange={e=>setItemDraft(e.target.value)} placeholder="Add item"/><button type="submit"><Plus size={16}/></button></form></main>;
 return <main className="travel-lists"><button className="tl-back" onClick={onClose}><ArrowLeft size={15}/> Home</button><header className="tl-header"><div><span>LIST</span><h1>{trip.title}</h1><p>{all} / {total} &nbsp; · &nbsp; {pct(all,total)}%</p></div></header><div className="tl-progress"><i style={{width:pct(all,total)+'%'}}/></div><section className="tl-grid">{lists.slice().sort((a,b)=>a.sortOrder-b.sortOrder).map(list=>{const st=listStats(list);return <button className="tl-card" key={list.id} onClick={()=>setSelected(list.id)}><div><strong>{list.name}</strong><span>{st.completed} / {st.total}</span></div><div className="tl-card-bottom"><i><b style={{width:pct(st.completed,st.total)+'%'}}/></i><ChevronRight size={16}/></div></button>})}</section><div className="tl-actions"><button className="tl-primary" onClick={()=>setShowTemplates(true)}><Plus size={15}/> Templates</button><button onClick={addNew}><Plus size={15}/> Blank List</button><button onClick={()=>{setSourceTripId('');setChecked([]);setShowSources(true)}}><Copy size={15}/> From Previous Trips</button></div>{showTemplates&&<div className="tl-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setShowTemplates(false)}}><section className="tl-modal tl-template-modal"><header><div><span>TEMPLATES</span><h2>Reusable Travel Lists</h2><p className="tl-modal-sub">Start with a built-in list, then edit it for this trip.</p></div><button onClick={()=>setShowTemplates(false)}><X size={17}/></button></header><div className="tl-template-grid">{TRAVEL_LIST_TEMPLATES.map(template=><button className="tl-template-card" key={template.id} onClick={()=>addTemplate(template)}><div><strong>{template.name}</strong><small>{template.description}</small></div><span>{template.items.length} items</span></button>)}</div></section></div>}{showSources&&<div className="tl-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setShowSources(false)}}><section className="tl-modal"><header><div><span>REUSE</span><h2>From Previous Trips</h2></div><button onClick={()=>setShowSources(false)}><X size={17}/></button></header><select value={sourceTripId} onChange={e=>{setSourceTripId(e.target.value);setChecked([])}}><option value="">Choose a trip</option>{trips.filter(t=>t.id!==trip.id&&Array.isArray(t.lists)&&t.lists.length).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select>{sourceTripId&&<div className="tl-source-lists">{trips.find(t=>t.id===sourceTripId)?.lists.slice().sort((a,b)=>a.sortOrder-b.sortOrder).map(list=>{const st=listStats(list);const on=checked.includes(list.id);return <button className={on?'selected':''} key={list.id} onClick={()=>setChecked(v=>on?v.filter(x=>x!==list.id):[...v,list.id])}><span>{on?'✓':'○'}</span><strong>{list.name}</strong><small>{st.total} items</small></button>})}</div>}<button className="tl-copy" disabled={!checked.length} onClick={copySelected}><Copy size={15}/> Add selected lists</button></section></div>}</main>;
}
