import React, { useMemo } from 'react';
import { Calendar, ChevronRight, Plus, Database } from 'lucide-react';
import './Home.css';

type TripStatus = 'planning' | 'traveling' | 'achieve';
interface Trip { id:string; name:string; subtitle:string; startDate:string; endDate:string; destinations:string[]; status:TripStatus; lastEditedAt:number; coverImage:string; scriptText?:string; ledger?:any[] }

const readPlans=():Trip[]=>{try{const raw=localStorage.getItem('vela.plans.v1');const plans=raw?JSON.parse(raw):[];return Array.isArray(plans)?plans.map((t:any)=>({...t,status:['traveling','travelling','in progress'].includes(String(t.status).toLowerCase())?'traveling':['achieve','achieved','completed'].includes(String(t.status).toLowerCase())?'achieve':'planning',subtitle:t.subtitle||'',destinations:Array.isArray(t.destinations)?t.destinations:[],lastEditedAt:Number(t.lastEditedAt||t.updatedAt||t.createdAt||0),coverImage:t.coverImage||''})):[]}catch{return[]}};
const fmt=(v:string)=>{const m=String(v||'').match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[1]}.${m[2]}.${m[3]}`:String(v||'')};
const dates=(t:Trip)=>t.startDate&&t.endDate?`${fmt(t.startDate)} — ${fmt(t.endDate)}`:t.startDate?fmt(t.startDate):'DATES NOT SET';
const destination=(t:Trip)=>{const d=t.destinations.join(' · ');return d&&d.toLowerCase()!==t.name.trim().toLowerCase()?d:''};
const dayCount=(t:Trip)=>{if(!t.startDate||!t.endDate)return '';const a=new Date(`${t.startDate}T00:00:00`),b=new Date(`${t.endDate}T00:00:00`);const n=Math.round((b.getTime()-a.getTime())/86400000)+1;return n>0?`${n} DAYS`:''};
const summary=(t:Trip)=>{const local:Record<string,number>={};let cny=0;(Array.isArray(t.ledger)?t.ledger:[]).forEach((e:any)=>{const a=Number(e.amount)||0,c=String(e.currency||'').toUpperCase();if(c&&c!=='CNY')local[c]=(local[c]||0)+a;if(String(e.finalCurrency||'').toUpperCase()==='CNY'&&e.finalAmount!=null)cny+=Number(e.finalAmount)||0;else if(c==='CNY')cny+=a});return[dayCount(t),Object.entries(local).map(([c,a])=>`${c} ${Math.round(a).toLocaleString('en-US')}`).join(' · '),cny?`¥${Math.round(cny).toLocaleString('en-US')}`:''].filter(Boolean).join(' · ')};

function goTrip(id:string){localStorage.setItem('vela.trip.current.v1',id);const p=readPlans().find(x=>x.id===id);if(p)localStorage.setItem('vela.plan.v1',JSON.stringify(p));window.location.reload()}
function newTrip(){const id=crypto.randomUUID();const me={id:crypto.randomUUID(),name:'Me',ratio:100};const trip:any={id,name:'New Journey',startDate:'',endDate:'',destinations:[],settlementCurrency:'CNY',status:'planning',lastEditedAt:Date.now(),coverImage:'',members:[me],accounts:[{id:crypto.randomUUID(),name:'Cash'},{id:crypto.randomUUID(),name:'Bank Card'},{id:crypto.randomUUID(),name:'Alipay'},{id:crypto.randomUUID(),name:'WeChat Pay'}],events:[],ledger:[]};const plans=readPlans();localStorage.setItem('vela.plans.v1',JSON.stringify([trip,...plans]));goTrip(id)}

export default function Home(){const plans=useMemo(()=>readPlans(),[]);const active=plans.filter(t=>t.status!=='achieve');const traveling=active.find(t=>t.status==='traveling');const planning=active.filter(t=>t.status==='planning').sort((a,b)=>b.lastEditedAt-a.lastEditedAt);const current=traveling||planning[0]||null;const next=planning.filter(t=>t.id!==current?.id).slice(0,2);const achieved=plans.filter(t=>t.status==='achieve').sort((a,b)=>b.lastEditedAt-a.lastEditedAt).slice(0,2);
 const nav=(label:string)=>{document.querySelectorAll<HTMLButtonElement>('.bottom-nav button').forEach(b=>{if(b.textContent?.trim().startsWith(label))b.click()})};
 const card=(t:Trip,compact=false)=><div className={compact?'vela-compact-card':'vela-hero-card'} onClick={()=>goTrip(t.id)}>{compact?<><img className="vela-compact-img" src={t.coverImage||''} /><div className="vela-compact-content"><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start'}}><h3 className="vela-compact-title">{t.name}</h3><span className="vela-badge">{t.status}</span></div>{t.subtitle&&t.subtitle!==t.name&&<div className="vela-compact-subtitle">{t.subtitle}</div>}<div className="vela-date"><Calendar size={12}/>{dates(t)}</div>{summary(t)&&<small className="vela-summary">{summary(t)}</small>}</div><ChevronRight size={16}/></>:<><div className="vela-hero-content"><div className="vela-hero-label">CURRENT TRIP <span className="vela-status-dot green"/></div><div className="vela-hero-sublabel">{t.status}</div><h2 className="vela-hero-title">{t.name}</h2>{t.subtitle&&t.subtitle!==t.name&&<div className="vela-hero-subtitle">{t.subtitle}</div>}<div className="vela-date"><Calendar size={14}/>{dates(t)}</div>{summary(t)&&<div className="vela-summary">{summary(t)}</div>}<div className="vela-hero-tether"><span><Database size={14}/> Quick Entry will be recorded<br/>to this trip</span><ChevronRight size={14}/></div></div><div className="vela-hero-image-wrapper" style={t.coverImage?{backgroundImage:`url("${t.coverImage}")`}:undefined}><div className="vela-hero-index">01</div>{t.scriptText&&<div className="vela-hero-script">{t.scriptText}</div>}</div></>};
 return <div className="vela-app-container"><header className="vela-header"><div className="vela-brand"><h1>Vela <span>/ JOURNEYS</span></h1><div className="vela-subtitle">TRAVEL · RECORD · BELONG</div></div><div className="vela-header-actions"><div className="vela-trip-count"><strong>{active.length}</strong> TRIPS</div><button className="vela-all-trips" onClick={()=>document.querySelector<HTMLButtonElement>('[data-vela-all]')?.click()}>ALL TRIPS</button><button className="vela-add-btn" onClick={newTrip}><Plus size={18}/></button></div></header>{current&&<section className="vela-hero-section">{card(current)}</section>}{next.length>0&&<section className="vela-list-section"><div className="vela-list-header"><div className="vela-list-title">PLANNING NEXT</div><button className="vela-view-all" onClick={()=>document.querySelector<HTMLButtonElement>('[data-vela-all]')?.click()}>View all <ChevronRight size={14}/></button></div>{next.map(t=><div key={t.id}>{card(t,true)}</div>)}</section>}{achieved.length>0&&<section className="vela-list-section"><div className="vela-list-header"><div className="vela-list-title">RECENT JOURNEYS</div></div>{achieved.map(t=><div key={t.id}>{card(t,true)}</div>)}</section>} {!current&&<section className="vela-empty"><p>YOUR NEXT JOURNEY AWAITS.</p><button onClick={newTrip}><Plus size={15}/> NEW TRIP</button></section>}<div className="vela-bottom-scenery"><div className="vela-scenery-text">FURTHER<br/>BRIGHTER<br/>TOGETHER</div><div className="vela-ufo-wrapper" onClick={()=>document.querySelector<HTMLButtonElement>('.home-quick')?.click()}><div className="vela-ufo-btn"><span>🛸</span></div><div className="vela-ufo-label">QUICK ENTRY</div></div></div><nav className="vela-bottom-nav">{['Home','Ledger','Balance','Logbook','Atelier'].map(x=><button key={x} className={`vela-nav-item ${x==='Home'?'active':''}`} onClick={()=>x==='Home'?null:nav(x)}><span className="vela-nav-icon">{x==='Home'?'⌂':x==='Ledger'?'▤':x==='Balance'?'⚖':x==='Logbook'?'◎':'⌘'}</span>{x}</button>)}</nav></div>}
